site_name: Cloudbreak 1.3.0
site_url: http://sequenceiq.com/cloudbreak-docs
repo_url: https://github.com/sequenceiq/cloudbreak-docs
theme: mkdocs
theme_dir: mkdocs_theme
dev_addr: 0.0.0.0:8000
markdown_extensions:
    - markdown_include.include
pages:
    - Intro:
        - Overview: index.md
        - Architecture: architecture.md
    - Setup:
        - Your Own VM: onprem.md
        - AWS: aws.md
        - Azure: azure.md
        - GCP: gcp.md
        - OpenStack: openstack.md
        - Mesos (TP): mesos.md
        - Update Cloudbreak: update.md
    - Configuration:
        - Account Management: ui_account.md
        - Basic Configuration: operations.md
        - Advanced Configuration: configuration.md
        - Custom Cloud Images: images.md
        - Auto-Scaling: periscope.md
        - Recipes: recipes.md
        - Platform Tagging (TP): topologies.md
        - Kerberos (TP): kerberos.md
        - Ambari Database: database.md
        - Development:
            - Environments: environments.md
            - Flows: flow.html
    - Reference:
        - API: api.md
        - Cloudbreak Shell: shell.md
        - Blueprints: blueprints.md
        - SPI: spi.md
    - Release Notes:        
        - Release Notes: releasenotes.md
        - Known Issues: issues.md
        - Change Log: changelog.md